# Generated by Django 5.0.1 on 2024-01-31 19:35

import datetime
import django.db.models.deletion
import loopers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(default=1, max_length=255)),
                ('email_validated', models.BooleanField(default=False)),
                ('loop_count', models.IntegerField(default=0)),
                ('change_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('friends', models.ManyToManyField(blank=True, to='loopers.caddy')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop_title', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today, validators=[loopers.models.no_future_loop_date])),
                ('num_loops', models.IntegerField(default=1, verbose_name='Number of loops')),
                ('money', models.IntegerField(verbose_name='Money made')),
                ('notes', models.TextField(blank=True)),
                ('caddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
