# Generated by Django 5.0.1 on 2024-02-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loopers', '0002_caddy_change_email_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caddy',
            name='change_email_key',
            field=models.CharField(blank=True, default=1, max_length=255, null=True),
        ),
    ]
