# Generated by Django 5.0.1 on 2024-06-19 21:30

import caddymaster.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loopers', '0002_alter_caddy_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaddyMaster',
            fields=[
                ('caddy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loopers.caddy')),
            ],
            options={
                'permissions': [('can_assign_loops', 'Can assign loops')],
            },
            bases=('loopers.caddy',),
        ),
        migrations.CreateModel(
            name='CaddyShack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caddy_shack_title', models.CharField(max_length=100)),
                ('caddy_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddymaster.caddymaster')),
                ('caddys', models.ManyToManyField(related_name='caddys_in_shack', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golfers', models.JSONField()),
                ('time', models.DateField(default=datetime.date.today)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('flight', models.CharField(blank=True, max_length=4)),
                ('caddy', models.ForeignKey(on_delete=models.SET(caddymaster.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('caddy_shack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddymaster.caddyshack')),
            ],
        ),
    ]
