# Generated by Django 5.0.1 on 2024-06-18 01:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loopers', '0002_alter_caddy_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaddyMaster',
            fields=[
                ('caddy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loopers.caddy')),
            ],
            options={
                'permissions': [('can_assign_loops', 'Can assign loops')],
            },
            bases=('loopers.caddy',),
        ),
        migrations.CreateModel(
            name='TeeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golfers', models.JSONField()),
                ('time', models.DateField(default=datetime.date.today)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('flight', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaddyShack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caddy_shack_title', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('golfer_groups', models.JSONField(null=True)),
                ('caddy_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caddymaster.caddymaster')),
                ('caddys', models.ManyToManyField(blank=True, related_name='caddys_in_shack', to='loopers.caddy')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
