# Generated by Django 5.0.1 on 2024-06-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddymaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teetime',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
