# Generated by Django 5.0.1 on 2024-03-14 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddymaster', '0001_initial'),
        ('loopers', '0002_alter_caddy_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caddyshack',
            name='caddys',
            field=models.ManyToManyField(blank=True, to='loopers.caddy'),
        ),
        migrations.AlterField(
            model_name='caddymaster',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
