# Generated by Django 5.0.1 on 2024-06-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddymaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teetime',
            name='caddy',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
