# Generated by Django 5.0.1 on 2024-06-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddymaster', '0002_alter_teetime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teetime',
            name='golfers',
            field=models.CharField(max_length=100),
        ),
    ]
