# Generated by Django 5.0.1 on 2024-07-04 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caddymaster', '0003_alter_teetime_golfers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caddymaster',
            options={'permissions': [('can_create_teetimes', 'Can create Teetimes')]},
        ),
    ]
