# Generated by Django 5.0.1 on 2024-07-08 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddymaster', '0004_alter_caddymaster_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teetime',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 8, 0)),
        ),
    ]
