# Generated by Django 5.0.1 on 2024-07-12 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddymaster', '0005_alter_teetime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caddyshack',
            name='caddy_shack_title',
            field=models.CharField(max_length=100, verbose_name='Caddy Shack'),
        ),
        migrations.AlterField(
            model_name='teetime',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 8, 0)),
        ),
    ]
